version: '3.9'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://user:pass@db:5432/hotdog
      - ALLOWED_ORIGINS=["http://localhost:3000","http://localhost:5173"]
      - VERSION=docker-dev
    env_file:
      - .env.docker
    depends_on:
      - db
    volumes:
      - ./src:/app/src   # для разработки (hot-reload)
      - ./test:/app/test
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: hotdog
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
