services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      ML_SERVICE_URL: http://ml:8001
    depends_on:
      - ml

  front:
    build: ./src/front
    ports:
      - "3000:3000"
    environment:
      VITE_API_TARGET: http://api:8000
    depends_on:
      - api

  ml:
    build:
      context: .
      dockerfile: ml/Dockerfile.stub
    ports:
      - "8001:8001"
